#!/bin/sh
#git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
mkdir -p build/bin
mkdir -p build/lib
export PYENV_ROOT="$HOME/.pyenv" && \
export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"
#pyenv install ${PYTHON_VERSION}
ls -ltrh $HOME/.pyenv/versions/${PYTHON_VERSION}
./$HOME/.pyenv/versions/${PYTHON_VERSION}/bin/pip install -r requirements.txt
cp -r $PYENV_ROOT build/pyenv
cd build/bin
ln -s ../pyenv/versions/${PYTHON_VERSION}/bin/python python
ln -s ../pyenv/versions/${PYTHON_VERSION}/bin/pip pip

