#!/bin/sh
git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
export PYENV_ROOT="$HOME/.pyenv" && \
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)" 
pyenv install ${PYTHON_VERSION}
mkdir -p build/bin
mkdir -p build/lib
cp -r $PYENV_ROOT build/pyenv
cp  binary_shim build/bin
cd build
ln -s ./binary_shim python
ln -s ./binary_shim pip
pwd

